spring.application.name=Proyecto1Bases

# ── DataSource SQL Server ──────────────────────────────────────────
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuinielaFutbol;encrypt=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ── JPA / Hibernate ───────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.format_sql=true

# ── Thymeleaf ─────────────────────────────────────────────────────
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ── Server ────────────────────────────────────────────────────────
server.port=8080
